packages:
  - apps/*
  - packages/*
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - ffmpeg-static
  - sharp
overrides:
  kysely: 0.28.17
  "@types/react": "~19.2.2"
  "@types/react-dom": "~19.2.2"
