import { GRID_GAP, NARROW_TITLE_FONT_SIZE, NARROW_WIDGET_MAX_WIDTH } from "../stat/constants";

export { GRID_GAP, NARROW_TITLE_FONT_SIZE, NARROW_WIDGET_MAX_WIDTH };

export const LIFETIME_WIDE_GRID_MIN_WIDTH = 350;

export const LIFETIME_LABEL_FONT_DEFAULT = 11;
export const LIFETIME_LABEL_FONT_WIDE = 9;

export const LIFETIME_VALUE_FONT_WIDE = 28;
export const LIFETIME_VALUE_FONT_MEDIUM = 22;
export const LIFETIME_VALUE_FONT_NARROW = 11;
