import { NARROW_TITLE_FONT_SIZE, NARROW_WIDGET_MAX_WIDTH } from "../stat/constants";

export { NARROW_TITLE_FONT_SIZE, NARROW_WIDGET_MAX_WIDTH };

export const LIFETIME_WIDE_GRID_MIN_WIDTH = 350;

export const LIFETIME_COMPACT_WIDTH = 300;
export const LIFETIME_COMPACT_HEIGHT_2X3 = 330;
export const LIFETIME_COMPACT_HEIGHT_3X2 = 230;

export const LIFETIME_GRID_GAP = 8;
export const LIFETIME_GRID_GAP_COMPACT = 4;

export const LIFETIME_CARD_PADDING = 10;
export const LIFETIME_CARD_PADDING_COMPACT = 5;

export const LIFETIME_CARD_INNER_GAP = 4;
export const LIFETIME_CARD_INNER_GAP_COMPACT = 2;

export const LIFETIME_LABEL_FONT_DEFAULT = 11;
export const LIFETIME_LABEL_FONT_WIDE = 9;
export const LIFETIME_LABEL_FONT_TINY = 8;

export const LIFETIME_VALUE_FONT_WIDE = 28;
export const LIFETIME_VALUE_FONT_MEDIUM = 22;
export const LIFETIME_VALUE_FONT_NARROW = 11;
export const LIFETIME_VALUE_FONT_TINY = 9;
